numero = int(input('Insere um número para ver a sua tabuada: '))

print(f'A tabuada do {numero} é:')
print('-' * 13)
print(f'{numero} x  1 = {numero*1}')
print(f'{numero} x  2 = {numero*2}')
print(f'{numero} x  3 = {numero*3}')
print(f'{numero} x  4 = {numero*4}')
print(f'{numero} x  5 = {numero*5}')
print(f'{numero} x  6 = {numero*6}')
print(f'{numero} x  7 = {numero*7}')
print(f'{numero} x  8 = {numero*8}')
print(f'{numero} x  9 = {numero*9}')
print(f'{numero} x 10 = {numero*10}')
print(f'{numero} x 11 = {numero*11}')
print(f'{numero} x 12 = {numero*12}')
print('-' * 13)
